# ============================================================================
# Whole Gazebo Tall - Gazebo/RViz primitive obstacle config
# ============================================================================

world_model:
  coll_objs:
    sphere:
      sphere1:
        radius: 0.1
        position: [0.4, 0.4, 0.1]

    cube:
      cube1:
        dims: [0.3, 0.1, 0.6]
        pose: [0.4, 0.2, 0.2, 0.0, 0.0, 0.0, 1.0]

      cube2:
        dims: [0.3, 0.1, 0.6]
        pose: [0.4, -0.3, 0.2, 0.0, 0.0, 0.0, 1.0]

      ground:
        dims: [2.0, 2.0, 0.2]
        pose: [0.0, 0.0, -0.1, 0.0, 0.0, 0.0, 1.0]
